// <auto-generated />
using System;
using AudioGeraImagemWorker.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioGeraImagemWorker.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313002927_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioGeraImagemWorker.Domain.Entities.Comando", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InstanteAtualizacao")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("InstanteCriacao")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("TextoProcessado")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("UrlAudio")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("VARCHAR(MAX)");

                    b.HasKey("Id");

                    b.ToTable("Comandos", (string)null);
                });

            modelBuilder.Entity("AudioGeraImagemWorker.Domain.Entities.Comando", b =>
                {
                    b.OwnsMany("AudioGeraImagemWorker.Domain.Entities.ProcessamentoComando", "ProcessamentosComandos", b1 =>
                        {
                            b1.Property<Guid>("ComandoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("VARCHAR(20)");

                            b1.Property<DateTime>("InstanteCriacao")
                                .HasColumnType("DATETIME2");

                            b1.Property<string>("MensagemErro")
                                .HasColumnType("VARCHAR(256)");

                            b1.HasKey("ComandoId", "Id");

                            b1.ToTable("ProcessamentoComandos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ComandoId");
                        });

                    b.Navigation("ProcessamentosComandos");
                });
#pragma warning restore 612, 618
        }
    }
}
